import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "pt" | "en" | "es";

export const translations = {
  pt: {
    // Modal Configurações
    settingsTitle: "Configurações",
    settingsSubtitle: "Ajuste o idioma, timbres de áudio e volumes do aplicativo",
    appLanguage: "Idioma do Aplicativo",
    ptBr: "Português (Brasil)",
    enUs: "Inglês (English)",
    esEs: "Espanhol (Español)",
    audioVolume: "Controles de Volume",
    metronomeVol: "Volume do Metrônomo",
    metronomeVolLabel: "Volume do Metrônomo",
    testMetronome: "Testar Metrônomo",
    testMetronomeBtn: "Testar Metrônomo",
    instrumentVolLabel: "Volume dos Acordes / Instrumento",
    highGain: "Ganho Alto",
    defaultGain: "Padrão",
    previewChordBtn: "Ouvir Acorde",
    volumePresets: "Predefinições:",
    softVolume: "70% Suave",
    standardVolume: "100% Padrão",
    boostVolume: "🚀 150% Ganho Alto (Celular)",
    soundBankTitle: "Timbres & Banco de Sons",
    timbresAvailable: "6 Timbres Disponíveis",
    webAudioSynth: "Sintetizador WebAudio de Baixa Latência",
    doneBtn: "Concluído",
    masterVol: "Volume Geral",
    synthesizers: "Sintetizadores & Timbres",
    synthDesc: "Escolha o som padrão para o Círculo Harmônico, Teclado e Violão",

    // Header & Controls
    appSubtitle: "Círculo de Campos Harmônicos",
    studyModeBtn: "Estudo",
    studyTitle: "Modo Estudo",
    degreesBtn: "Graus",
    vocalTunerBtn: "Afinador Vocal",
    soundToggle: "Som",
    muteSound: "Desativar som",
    enableSound: "Ativar som",
    toggleTheme: "Alternar Tema (Claro/Escuro)",
    loadingTitle: "Carregando Workestra",
    loadingStudio: "Carregando estúdio harmônico...",

    // Mode & Chord Types
    majorField: "CAMPO MAIOR",
    minorField: "CAMPO MENOR",
    triads: "Tríades (3 notas)",
    tetrads: "Tétrades (com 7ª)",
    major: "Maior",
    minor: "Menor",

    // Key Readout
    tonality: "Tonalidade",
    relative: "Relativa",
    hiddenTonality: "Tonalidade Oculta (Desafio)",
    modeEstudoActive: "Modo Estudo Ativo",
    hideAll: "Ocultar todos",
    diagramClosed: "Diagrama fechado. Clique em qualquer acorde acima para ver suas notas e posições.",
    reopenDiagram: "Reabrir Diagrama",
    studyModeActiveNote: "Modo Estudo Ativo: Informações de graus e notas ocultadas! Clique nos botões para ouvir o som ou observe a posição no círculo para adivinhar antes de revelar.",
    studyModeHint: "Clique no acorde misterioso para ouvir o som e testar seu palpite",
    standardDegrees: "Graus: I · II · III · IV · V · VI · VII",
    clickChordToSee: "Clique no acorde para ver o diagrama",

    // Auth
    loginWithGoogle: "Entrar com Google",
    connectedViaGoogle: "Conectado via Google",
    signOut: "Sair da conta",
    user: "Usuário",
    musician: "Músico",
    welcomeTitle: "Bem-vindo(a)!",
    connectAccount: "Conecte sua conta para começar seus estudos",
    connecting: "Conectando ao Google...",
    heroBadge: "Estúdio Harmônico Completo",
    heroHeading: "Domine harmonia musical com precisão e clareza.",
    heroSub: "Gire a roda harmônica em tempo real, visualize graus da escala no teclado e no violão com timbres acústicos reais e treine seu ouvido.",
    privacy: "Privacidade",
    terms: "Termos",

    // Chord Inspector Modal / Card
    theoreticalTriad: "Tríade Teórica",
    on6Strings: "Nas 6 Cordas",
    sounding: "que soam",
    degreeWord: "Grau",
    notesWord: "notas",
    chordRevealed: "Acorde Revelado",
    hide: "Ocultar",
    whichChordGuess: "Qual acorde você ouve / identifica?",
    wrongGuessMsg: "Não é este acorde. Ouça novamente ou observe a posição no círculo!",
    correctGuessMsg: "🎉 Correto! Revelando diagrama...",
    revealDiagramBtn: "Revelar diagrama e notas",
    playChordBtn: "Tocar Acorde",
    listenArpeggio: "Ouvir Arpejo (Corda por Corda)",
    arpeggiatingStrings: "Arpejando cordas...",
    arpeggiatingNotes: "Arpejando notas...",
    listenArpeggioPiano: "Ouvir Arpejo",
    roleInKey: "Papel no tom de",
    inversionNotice: "Inversão & Cifra Composta",
    inversionNoticeGuitar: "Na teoria musical, a inversão altera a nota do baixo (ex: C/E = Dó com baixo em Mi). No violão, o diagrama exibe a digitação exata das cordas e dedos!",
    inversionNoticePiano: "Na teoria musical, a inversão altera a nota do baixo (ex: C/E = Dó com baixo em Mi). No teclado, as teclas destacam a nova ordem das notas!",
    guitarFretboardTitle: "Diagrama de Violão (Cifras & Braço)",
    guitarFretboardSub: "🎸 Toque nas cordas ou bolinhas para soar · 1=Indicador · 2=Médio · 3=Anelar · 4=Mindinho",
    keyboardHandTitle: "Diagrama de Teclado (1 Mão)",
    rightHandFingers: "Mão Direita: Dedos 1 (polegar) · 3 (médio) · 5 (mínimo)",
    simultaneous4: "4 notas simultâneas",
    simultaneous3: "3 notas simultáneas",
    keysTopNote: "Topo das teclas: Graus da escala de",
    notesStructure: "Notas & Estrutura do Acorde",
    stringNeck: "Corda (Braço)",
    tapToPlaySingle: "Toque para ouvir a nota individual 👆",
    mutedString: "✕ Abafada (Não toca)",
    openString: "Corda Solta (0)",
    fretWord: "Casa",
    fingerWord: "Dedo",
    oneString: "1 corda:",
    multipleStrings: "cordas:",

    // Vocal Pitch Detector
    vocalDetectorTitle: "Detector Vocal & Afinador de Tom",
    vocalDetectorSubtitle: "Descubra o tom da sua voz e afine em tempo real",
    aiWebAudio: "IA / Web Audio",
    enableMic: "Ativar Microfone & Cantar",
    disableMic: "Desativar Microfone",
    inTune: "AFINADO",
    sharp: "SUSTENIDO (Alto)",
    flat: "BEMOL (Baixo)",
    singANote: "Cante uma nota constante para medir",
    solfejoNotation: "Solfejo (Dó)",
    cifraNotation: "Cifra (C)",
    micGuideTitle: "Como Liberar o Microfone no seu Aparelho:",
    micGuideSubtitle: "O navegador ou sistema bloqueou o acesso ao microfone. Para liberar em 5 segundos:",

    // Chord Map Atlas
    chordMapTitle: "Mapa Visual de Acordes",
    chordMapSubtitle: "Atlas harmônico completo com digitação para Teclado e Violão",
    filterAll: "Todos os 7 Graus",
    filterTonic: "Tônica (I, III, VI)",
    filterSubdominant: "Subdominante (II, IV)",
    filterDominant: "Dominante (V, VII)",
    inversions: "Inversões",
    rootPosition: "Posição Fundamental",
    firstInversion: "1ª Inversão",
    secondInversion: "2ª Inversão",
    thirdInversion: "3ª Inversão",
    playAllCadence: "Ouvir Todos (I ➔ VII)",
    stopCadence: "Parar Cadência",

    // Capo Calculator
    capoTitle: "Calculadora de Capotraste",
    capoSubtitle: "Posições e digitações de acordes abertos para violão",
    fret: "Traste",
    difficulty: "Dificuldade",
    easy: "fácil",
    medium: "médio",
    advanced: "avançado",
    realKey: "Tom Real",
    quickSuggestions: "Sugestões Rápidas para Tom de",
    noCapo: "Sem Capo (Casa 0)",
    capoAtFret: "Capo na Casa",
    standard: "Padrão",
    recommended: "Recomendado",
    shapesOf: "Formas de",
    fretSelectorTitle: "Seletor da Casa do Capotraste:",
    openTuning: "Afinação Aberta (Casa 0)",
    howYouFretVsReal: "Como você digita (Shape) vs O que soa (Tom Real",
    clickToListen: "Clique para ouvir",
    fretLabel: "Digitar:",
    soundsLabel: "Soa:",

    // Progression Player
    progressionTitle: "Progressões Harmônicas & Sequenciador",
    progressionSubtitle: "Biblioteca de louvores e criador de sequências",
    presetsTab: "Biblioteca Clássica & Gospel",
    customTab: "Criador Próprio",
    play: "Tocar",
    stop: "Parar",
    bpm: "BPM (Andamento)",
    loop: "Loop",
    metronome: "Metrônomo",
    songNamePlaceholder: "Nome da sua música...",
    save: "Salvar",
    clear: "Limpar",
    tapToAddDegree: "Toque para adicionar grau à sequência",
    slashChordsSubtitle: "Acordes Compostos / Baixos em Barra (Ex: D/F#, G/B):",
    yourSavedProgressions: "Suas Progressões Salvas:",
    chordsWord: "acordes",
    noChordsInSequence: "Nenhum acorde na sequência. Toque nos botões de graus acima para adicionar!",
    remove: "remover",
    copyChords: "Copiar Cifra",
    copied: "Copiado!",

    // Harmonic Quiz
    quizTitle: "Treino Auditivo & Quiz Harmônico",
    quizSubtitle: "Aprenda a tirar músicas de ouvido e decorar os graus",
    startQuiz: "Novo Desafio",
    score: "Pontuação",
    streak: "Sequência",
    correct: "Correto!",
    wrong: "Tente Novamente",
    quizDegreeEar: "Ouvido (Graus)",
    quizRelatives: "Relativos",
    quizFunctions: "Funções",
    quizMixed: "Misto",
    harmonicChallenge: "Desafio Harmônico",
    referenceTonic: "1º Tônica",
    mysteryChord: "2º Acorde Misterioso",
    nextQuestion: "Próxima Pergunta",

    // Common
    piano: "Teclado",
    guitar: "Violão",
    close: "Fechar",
  },
  en: {
    // Modal Configurações
    settingsTitle: "Settings",
    settingsSubtitle: "Adjust app language, audio timbres, and volume controls",
    appLanguage: "App Language",
    ptBr: "Portuguese (Português)",
    enUs: "English",
    esEs: "Spanish (Español)",
    audioVolume: "Volume Controls",
    metronomeVol: "Metronome Volume",
    metronomeVolLabel: "Metronome Volume",
    testMetronome: "Test Metronome",
    testMetronomeBtn: "Test Metronome",
    instrumentVolLabel: "Chord / Instrument Volume",
    highGain: "High Gain",
    defaultGain: "Default",
    previewChordBtn: "Preview Chord",
    volumePresets: "Presets:",
    softVolume: "70% Soft",
    standardVolume: "100% Standard",
    boostVolume: "🚀 150% High Gain (Mobile)",
    soundBankTitle: "Timbres & Sound Bank",
    timbresAvailable: "6 Available Timbres",
    webAudioSynth: "Low Latency WebAudio Synth",
    doneBtn: "Done",
    masterVol: "Master Volume",
    synthesizers: "Synthesizers & Timbres",
    synthDesc: "Choose default sound for Harmonic Wheel, Keyboard, and Guitar",

    // Header & Controls
    appSubtitle: "Harmonic Field Circle",
    studyModeBtn: "Study",
    studyTitle: "Study Mode",
    degreesBtn: "Degrees",
    vocalTunerBtn: "Vocal Tuner",
    soundToggle: "Sound",
    muteSound: "Mute sound",
    enableSound: "Enable sound",
    toggleTheme: "Toggle Theme (Light/Dark)",
    loadingTitle: "Loading Workestra",
    loadingStudio: "Loading harmonic studio...",

    // Mode & Chord Types
    majorField: "MAJOR FIELD",
    minorField: "MINOR FIELD",
    triads: "Triads (3 notes)",
    tetrads: "Tetrads (with 7th)",
    major: "Major",
    minor: "Minor",

    // Key Readout
    tonality: "Key",
    relative: "Relative",
    hiddenTonality: "Hidden Key (Challenge)",
    modeEstudoActive: "Study Mode Active",
    hideAll: "Hide all",
    diagramClosed: "Diagram closed. Click any chord above to view its notes and fingerings.",
    reopenDiagram: "Reopen Diagram",
    studyModeActiveNote: "Study Mode Active: Degree and note information hidden! Click buttons to hear sound or observe position on wheel to guess before revealing.",
    studyModeHint: "Click mysterious chord to hear sound and test your guess",
    standardDegrees: "Degrees: I · II · III · IV · V · VI · VII",
    clickChordToSee: "Click chord to view diagram",

    // Auth
    loginWithGoogle: "Sign in with Google",
    connectedViaGoogle: "Connected via Google",
    signOut: "Sign Out",
    user: "User",
    musician: "Musician",
    welcomeTitle: "Welcome!",
    connectAccount: "Connect your account to start studying",
    connecting: "Connecting to Google...",
    heroBadge: "Complete Harmonic Studio",
    heroHeading: "Master musical harmony with precision and clarity.",
    heroSub: "Spin the harmonic wheel in real time, visualize scale degrees on keyboard and guitar with real acoustic timbres, and train your ear.",
    privacy: "Privacy",
    terms: "Terms",

    // Chord Inspector Modal / Card
    theoreticalTriad: "Theoretical Triad",
    on6Strings: "On 6 Strings",
    sounding: "sounding",
    degreeWord: "Degree",
    notesWord: "notes",
    chordRevealed: "Revealed Chord",
    hide: "Hide",
    whichChordGuess: "Which chord do you hear / identify?",
    wrongGuessMsg: "Not this chord. Listen again or observe position on wheel!",
    correctGuessMsg: "🎉 Correct! Revealing diagram...",
    revealDiagramBtn: "Reveal diagram and notes",
    playChordBtn: "Play Chord",
    listenArpeggio: "Listen Arpeggio (String by String)",
    arpeggiatingStrings: "Arpeggiating strings...",
    arpeggiatingNotes: "Arpeggiating notes...",
    listenArpeggioPiano: "Listen Arpeggio",
    roleInKey: "Role in key of",
    inversionNotice: "Inversion & Slash Chord",
    inversionNoticeGuitar: "In music theory, inversion changes the bass note (e.g. C/E = C with E bass). On guitar, the diagram below shows exact fingerings!",
    inversionNoticePiano: "In music theory, inversion changes the bass note (e.g. C/E = C with E bass). On keyboard, keys highlight the new note order!",
    guitarFretboardTitle: "Guitar Fretboard Diagram",
    guitarFretboardSub: "🎸 Tap strings or frets to play · 1=Index · 2=Middle · 3=Ring · 4=Pinky",
    keyboardHandTitle: "Keyboard Diagram (1 Hand)",
    rightHandFingers: "Right Hand: Fingers 1 (thumb) · 3 (middle) · 5 (pinky)",
    simultaneous4: "4 simultaneous notes",
    simultaneous3: "3 simultaneous notes",
    keysTopNote: "Top of keys: Scale degrees of",
    notesStructure: "Notes & Chord Structure",
    stringNeck: "String (Neck)",
    tapToPlaySingle: "Tap to hear individual note 👆",
    mutedString: "✕ Muted (Does not play)",
    openString: "Open String (0)",
    fretWord: "Fret",
    fingerWord: "Finger",
    oneString: "1 string:",
    multipleStrings: "strings:",

    // Vocal Pitch Detector
    vocalDetectorTitle: "Vocal Pitch Detector & Tuner",
    vocalDetectorSubtitle: "Discover your vocal range and tune in real time",
    aiWebAudio: "AI / Web Audio",
    enableMic: "Enable Microphone & Sing",
    disableMic: "Disable Microphone",
    inTune: "IN TUNE",
    sharp: "SHARP (High)",
    flat: "FLAT (Low)",
    singANote: "Sing a steady note to measure",
    solfejoNotation: "Solfège (Do)",
    cifraNotation: "Chord Letters (C)",
    micGuideTitle: "How to Enable Microphone on your Device:",
    micGuideSubtitle: "Microphone access was blocked. To allow in 5 seconds:",

    // Chord Map Atlas
    chordMapTitle: "Visual Chord Map",
    chordMapSubtitle: "Complete harmonic atlas with fingerings for Keyboard & Guitar",
    filterAll: "All 7 Degrees",
    filterTonic: "Tonic (I, III, VI)",
    filterSubdominant: "Subdominant (II, IV)",
    filterDominant: "Dominant (V, VII)",
    inversions: "Inversions",
    rootPosition: "Root Position",
    firstInversion: "1st Inversion",
    secondInversion: "2nd Inversion",
    thirdInversion: "3rd Inversion",
    playAllCadence: "Play All (I ➔ VII)",
    stopCadence: "Stop Cadence",

    // Capo Calculator
    capoTitle: "Capo Calculator",
    capoSubtitle: "Open guitar chord shapes and capo positions for any key",
    fret: "Fret",
    difficulty: "Difficulty",
    easy: "easy",
    medium: "medium",
    advanced: "advanced",
    realKey: "Real Key",
    quickSuggestions: "Quick Suggestions for Key of",
    noCapo: "No Capo (Open)",
    capoAtFret: "Capo at Fret",
    standard: "Standard",
    recommended: "Recommended",
    shapesOf: "Shapes of",
    fretSelectorTitle: "Capo Fret Selector:",
    openTuning: "Open Tuning (Fret 0)",
    howYouFretVsReal: "How you fret (Shape) vs What sounds (Real Key",
    clickToListen: "Click to listen",
    fretLabel: "Fret:",
    soundsLabel: "Sounds:",

    // Progression Player
    progressionTitle: "Harmonic Progressions & Sequencer",
    progressionSubtitle: "Song library and custom sequence builder",
    presetsTab: "Classic & Gospel Library",
    customTab: "Custom Builder",
    play: "Play",
    stop: "Stop",
    bpm: "BPM (Tempo)",
    loop: "Loop",
    metronome: "Metronome",
    songNamePlaceholder: "Name of your song...",
    save: "Save",
    clear: "Clear",
    tapToAddDegree: "Tap degree to add to sequence",
    slashChordsSubtitle: "Slash Chords / Inverted Bass (e.g. D/F#, G/B):",
    yourSavedProgressions: "Your Saved Progressions:",
    chordsWord: "chords",
    noChordsInSequence: "No chords in sequence. Tap degree buttons above to add!",
    remove: "remove",
    copyChords: "Copy Chords",
    copied: "Copied!",

    // Harmonic Quiz
    quizTitle: "Ear Training & Harmonic Quiz",
    quizSubtitle: "Train your ear to recognize degrees and play by ear",
    startQuiz: "New Challenge",
    score: "Score",
    streak: "Streak",
    correct: "Correct!",
    wrong: "Try Again",
    quizDegreeEar: "Ear (Degrees)",
    quizRelatives: "Relatives",
    quizFunctions: "Functions",
    quizMixed: "Mixed",
    harmonicChallenge: "Harmonic Challenge",
    referenceTonic: "1st Tonic",
    mysteryChord: "2nd Mystery Chord",
    nextQuestion: "Next Question",

    // Common
    piano: "Keyboard",
    guitar: "Guitar",
    close: "Close",
  },
  es: {
    // Modal Configurações
    settingsTitle: "Configuraciones",
    settingsSubtitle: "Ajusta el idioma del app, timbres de audio y controles de volumen",
    appLanguage: "Idioma de la Aplicación",
    ptBr: "Portugués (Português)",
    enUs: "Inglés (English)",
    esEs: "Español",
    audioVolume: "Controles de Volumen",
    metronomeVol: "Volumen del Metrónomo",
    metronomeVolLabel: "Volumen del Metrónomo",
    testMetronome: "Probar Metrónomo",
    testMetronomeBtn: "Probar Metrónomo",
    instrumentVolLabel: "Volumen de Acordes / Instrumento",
    highGain: "Ganancia Alta",
    defaultGain: "Predeterminado",
    previewChordBtn: "Escuchar Acorde",
    volumePresets: "Ajustes:",
    softVolume: "70% Suave",
    standardVolume: "100% Estándar",
    boostVolume: "🚀 150% Ganancia Alta (Móvil)",
    soundBankTitle: "Timbres & Banco de Sonidos",
    timbresAvailable: "6 Timbres Disponibles",
    webAudioSynth: "Sintetizador WebAudio de Baja Latencia",
    doneBtn: "Hecho",
    masterVol: "Volumen General",
    synthesizers: "Sintetizadores & Timbres",
    synthDesc: "Elige el sonido predeterminado para el Círculo Armónico, Teclado y Guitarra",

    // Header & Controls
    appSubtitle: "Círculo de Campos Armónicos",
    studyModeBtn: "Estudio",
    studyTitle: "Modo Estudio",
    degreesBtn: "Grados",
    vocalTunerBtn: "Afinador Vocal",
    soundToggle: "Sonido",
    muteSound: "Desactivar sonido",
    enableSound: "Activar sonido",
    toggleTheme: "Cambiar Tema (Claro/Oscuro)",
    loadingTitle: "Cargando Workestra",
    loadingStudio: "Cargando estudio armónico...",

    // Mode & Chord Types
    majorField: "CAMPO MAYOR",
    minorField: "CAMPO MENOR",
    triads: "Tríadas (3 notas)",
    tetrads: "Tétradas (con 7ª)",
    major: "Mayor",
    minor: "Menor",

    // Key Readout
    tonality: "Tonalidad",
    relative: "Relativa",
    hiddenTonality: "Tonalidad Oculta (Desafío)",
    modeEstudoActive: "Modo Estudio Activo",
    hideAll: "Ocultar todos",
    diagramClosed: "Diagrama cerrado. Haz clic en cualquier acorde arriba para ver sus notas y posiciones.",
    reopenDiagram: "Reabrir Diagrama",
    studyModeActiveNote: "Modo Estudio Activo: ¡Información de grados y notas oculta! Haz clic en los botones para escuchar el sonido u observa la posición en el círculo para adivinhar antes de revelar.",
    studyModeHint: "Haz clic en el acorde misterioso para escuchar el sonido y probar tu adivinanza",
    standardDegrees: "Grados: I · II · III · IV · V · VI · VII",
    clickChordToSee: "Haz clic en el acorde para ver el diagrama",

    // Auth
    loginWithGoogle: "Iniciar sesión con Google",
    connectedViaGoogle: "Conectado con Google",
    signOut: "Cerrar sesión",
    user: "Usuario",
    musician: "Músico",
    welcomeTitle: "¡Bienvenido/a!",
    connectAccount: "Conecta tu cuenta para comenzar tus estudios",
    connecting: "Conectando a Google...",
    heroBadge: "Estudio Armónico Completo",
    heroHeading: "Domina la armonía musical con precisión y claridad.",
    heroSub: "Gira la rueda armónica en tiempo real, visualiza grados de la escala en teclado y guitarra con timbres acústicos reales y entrena tu oído.",
    privacy: "Privacidad",
    terms: "Términos",

    // Chord Inspector Modal / Card
    theoreticalTriad: "Tríada Teórica",
    on6Strings: "En las 6 Cuerdas",
    sounding: "que suenan",
    degreeWord: "Grado",
    notesWord: "notas",
    chordRevealed: "Acorde Revelado",
    hide: "Ocultar",
    whichChordGuess: "¿Qué acorde escuchas / identificas?",
    wrongGuessMsg: "No es este acorde. ¡Escucha de nuevo u observa la posición en el círculo!",
    correctGuessMsg: "🎉 ¡Correcto! Revelando diagrama...",
    revealDiagramBtn: "Revelar diagrama y notas",
    playChordBtn: "Tocar Acorde",
    listenArpeggio: "Escuchar Arpegio (Cuerda por Cuerda)",
    arpeggiatingStrings: "Arpegiando cuerdas...",
    arpeggiatingNotes: "Arpegiando notas...",
    listenArpeggioPiano: "Escuchar Arpegio",
    roleInKey: "Papel en el tono de",
    inversionNotice: "Inversión & Cifra Compuesta",
    inversionNoticeGuitar: "En la teoría musical, la inversión altera la nota del bajo (ej: C/E = Do con bajo en Mi). ¡En la guitarra, el diagrama muestra la digitación exacta!",
    inversionNoticePiano: "En la teoría musical, la inversión altera la nota del bajo (ej: C/E = Do con bajo en Mi). ¡En el teclado, las teclas destacan el nuevo orden!",
    guitarFretboardTitle: "Diagrama de Guitarra (Cifras y Mástil)",
    guitarFretboardSub: "🎸 Toca las cuerdas o trastes para sonar · 1=Índice · 2=Medio · 3=Anular · 4=Meñique",
    keyboardHandTitle: "Diagrama de Teclado (1 Mano)",
    rightHandFingers: "Mano Derecha: Dedos 1 (pulgar) · 3 (medio) · 5 (meñique)",
    simultaneous4: "4 notas simultáneas",
    simultaneous3: "3 notas simultáneas",
    keysTopNote: "Parte superior de las teclas: Grados de la escala de",
    notesStructure: "Notas & Estructura del Acorde",
    stringNeck: "Cuerda (Mástil)",
    tapToPlaySingle: "Toca para escuchar la nota individual 👆",
    mutedString: "✕ Apagada (No suena)",
    openString: "Cuerda Suelta (0)",
    fretWord: "Traste",
    fingerWord: "Dedo",
    oneString: "1 cuerda:",
    multipleStrings: "cuerdas:",

    // Vocal Pitch Detector
    vocalDetectorTitle: "Detector Vocal & Afinador de Tono",
    vocalDetectorSubtitle: "Descubre el tono de tu voz y afina en tiempo real",
    aiWebAudio: "IA / Web Audio",
    enableMic: "Activar Micrófono y Cantar",
    disableMic: "Desactivar Micrófono",
    inTune: "AFINADO",
    sharp: "SOSTENIDO (Alto)",
    flat: "BEMOL (Bajo)",
    singANote: "Canta una nota constante para medir",
    solfejoNotation: "Solfeo (Do)",
    cifraNotation: "Cifra (C)",
    micGuideTitle: "Cómo Habilitar el Micrófono en tu Dispositivo:",
    micGuideSubtitle: "El acceso al micrófono fue bloqueado. Para permitirlo en 5 segundos:",

    // Chord Map Atlas
    chordMapTitle: "Mapa Visual de Acordes",
    chordMapSubtitle: "Atlas armónico completo con digitación para Teclado y Guitarra",
    filterAll: "Todos los 7 Grados",
    filterTonic: "Tónica (I, III, VI)",
    filterSubdominant: "Subdominante (II, IV)",
    filterDominant: "Dominante (V, VII)",
    inversions: "Inversiones",
    rootPosition: "Posición Fundamental",
    firstInversion: "1ª Inversión",
    secondInversion: "2ª Inversión",
    thirdInversion: "3ª Inversión",
    playAllCadence: "Escuchar Todos (I ➔ VII)",
    stopCadence: "Detener Cadencia",

    // Capo Calculator
    capoTitle: "Calculadora de Capo",
    capoSubtitle: "Posiciones de capo y formas abiertas de guitarra para cada tono",
    fret: "Traste",
    difficulty: "Dificultad",
    easy: "fácil",
    medium: "medio",
    advanced: "avançado",
    realKey: "Tono Real",
    quickSuggestions: "Sugerencias Rápidas para Tono de",
    noCapo: "Sin Capo (Sueltas)",
    capoAtFret: "Capo en Traste",
    standard: "Estándar",
    recommended: "Recomendado",
    shapesOf: "Formas de",
    fretSelectorTitle: "Selector de Traste de Capo:",
    openTuning: "Afinación Abierta (Traste 0)",
    howYouFretVsReal: "Cómo digitas (Forma) vs Lo que suena (Tono Real",
    clickToListen: "Haz clic para escuchar",
    fretLabel: "Digitar:",
    soundsLabel: "Suena:",

    // Progression Player
    progressionTitle: "Progresiones Armónicas & Secuenciador",
    progressionSubtitle: "Biblioteca de canciones y creador de secuencias",
    presetsTab: "Biblioteca Clássica & Gospel",
    customTab: "Creador Propio",
    play: "Reproducir",
    stop: "Detener",
    bpm: "BPM (Tempo)",
    loop: "Repetir",
    metronome: "Metrónomo",
    songNamePlaceholder: "Nombre de tu canción...",
    save: "Guardar",
    clear: "Limpiar",
    tapToAddDegree: "Toca para añadir grado a la secuencia",
    slashChordsSubtitle: "Acordes Compuestos / Bajos Invertidos (ej: D/F#, G/B):",
    yourSavedProgressions: "Tus Progresiones Guardadas:",
    chordsWord: "acordes",
    noChordsInSequence: "Ningún acorde en la secuencia. ¡Toca los botones de grados arriba para añadir!",
    remove: "eliminar",
    copyChords: "Copiar Cifras",
    copied: "¡Copiado!",

    // Harmonic Quiz
    quizTitle: "Entrenamiento Auditivo & Quiz Harmónico",
    quizSubtitle: "Aprende a sacar canciones de oído y memorizar los grados",
    startQuiz: "Nuevo Desafío",
    score: "Puntuación",
    streak: "Racha",
    correct: "¡Correcto!",
    wrong: "Inténtalo de Nuevo",
    quizDegreeEar: "Oído (Grados)",
    quizRelatives: "Relativos",
    quizFunctions: "Funciones",
    quizMixed: "Mixto",
    harmonicChallenge: "Desafío Armónico",
    referenceTonic: "1ª Tónica",
    mysteryChord: "2º Acorde Misterioso",
    nextQuestion: "Siguiente Pregunta",

    // Common
    piano: "Teclado",
    guitar: "Guitarra",
    close: "Cerrar",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.pt) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("workestra_lang");
      if (saved === "pt" || saved === "en" || saved === "es") return saved;
      const navLang = navigator.language.toLowerCase();
      if (navLang.startsWith("es")) return "es";
      if (navLang.startsWith("en")) return "en";
    }
    return "pt";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("workestra_lang", lang);
    }
  };

  const t = (key: keyof typeof translations.pt): string => {
    const dict = translations[language] || translations.pt;
    return dict[key] || translations.pt[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
